### ISSUE TITLE
Store Push Notification Tokens in D.T Webapp

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#101]
We need to store the Expo Push Notification Token associated with a User's device to the D.T Webapp in order to enable D.T to send the user future push notifications (where appropriate in the workflow - should this be configurable? D.T question, not specific to mobile app)

For more information, please refer to Step 1 in the Expo Push Notifications guide:
https://docs.expo.io/versions/latest/guides/push-notifications/

![Screenshot from 2019-11-09 17-21-19](https://user-images.githubusercontent.com/191707/68535753-8348bc00-0315-11ea-9ca2-2e0715b33fbf.png)

**Comment by cairocoder01** [comment]
This is going to take modifications to either the [theme](https://github.com/DiscipleTools/disciple-tools-theme) or the [mobile app plugin](https://github.com/DiscipleTools/disciple-tools-mobile-app-plugin) (probably the latter would make the most sense). 

From what I understand, a few things will be needed:
1. An API endpoint to send the push token to and save it on the user. (This may need to be an array in order to allow users to login from multiple devices)
   * @j-oswin How would multiple devices be handled? If a user has created a push token on one device and then logs on using a different device, could we use that same push token on two devices, or do we need a unique push token for each device?
2. Integration into the notification processes within DT to use that push token to send the notification to Expo (and thus to the app).
3. Added user configuration within DT to select if they want to receive push notifications for different types of events.

@corsacca Since much of this will rely on your intervention and efforts in the mobile app plugin, what are your thoughts?

**Comment by corsacca** [comment]
Most of this functionality will be added by the mobile app plugin, but we need to add some filters or actions in strategic places in the theme as well.
1. There currently is an /user/update endpoint on the theme. We'll need to modify it with a filter to accept to accept custom fields. The app plugin will declare a push_tokens field for the update endpoint to use. An array sounds right.
2. We'll need to extend a few functions in `notifications.php` like `insert_notification_for_post_update` to allow the app plugin to decide whether to send a push notification.
3. This should probably be a setting in the app, that is save on the user. Step 2. would check the settings before sending a notification.

**Comment by cairocoder01** [comment]
@corsacca If you have issues for those items on the given repos, could you link to them from here? I think we'll have to wait to do any of the app stuff until those dependencies are ready.

For your point 3, do you think that should be part of the mobile app plugin and also stored as a custom field on the user? I would think that it would be nice for users to be able to configure all of their notifications from within the web app, although I'm not sure if you'd be able to conditionally add that into the UI or not. I could also see that it could make sense in the app itself in case people use it on multiple devices and want different settings per device (this is probably a rare case though)

**Comment by corsacca** [comment]
@cairocoder01 what is the hoped for timeline for the dependencies? I'll try to prioritize accordingly.

It would be great if notification settings were able to be set on the app and on the web with similar interfaces. I'll explore that as i add the needed filters for storing the token.

**Comment by cairocoder01** [comment]
@corsacca I think there is hope to do this in the next sprint, but since it will mostly depend on your side, you could tell us if that is reasonable for you to work on the web side of things. If you're not able to prioritize it that quickly, we'll just have to postpone the app side until the web dependency is done.

**Comment by corsacca** [comment]
@cairocoder01 I can have the api to add tokens and the api to update notification prefs done by tomorrow.
Would it also be on me to integrate the expo push notifications plugin to send the notifications?

**Comment by corsacca** [comment]
To add a push notification token
POST http://example.came/wp-json/dt/v1/user/update
```
{
  "add_push_token" : "token"
}
```
To remove a push token
POST http://example.came/wp-json/dt/v1/user/update
```
{
  "remove_push_token" : "token"
}
```

**Comment by corsacca** [comment]
Push notification preferences can be set on the web. We'll need to make those fields available for the app on an endpoint.

**Comment by corsacca** [comment]
https://github.com/DiscipleTools/disciple-tools-mobile-app-plugin/blob/3047878340a7ff716c36c81ce3e86eda3d773475/includes/functions.php#L118 Shows where the link to expo still needs to be set up.

**Comment by cairocoder01** [comment]
@corsacca To answer your questions from a few comments up: yes, I think the sending of notifications needs to be initiated from the web site. I haven't looked into what the whole process looks like though, so I can't say for sure. From the documentation @zdmc23 shared at the start of this thread, it looks like there is a composer package for PHP that could be used to trigger the notifications: https://docs.expo.io/versions/latest/guides/push-notifications/#2-call-expos-push-api-with-the.

**Comment by zdmc23** [comment]
> To add a push notification token
> POST http://example.came/wp-json/dt/v1/user/update
> 
> ```
> {
>   "add_push_token" : "token"
> }
> ```
> 
> To remove a push token
> POST http://example.came/wp-json/dt/v1/user/update
> 
> ```
> {
>   "remove_push_token" : "token"
> }
> ```

Hi @j-oswin , is this something that you'd be willing to implement in the mobile app?

**Comment by corsacca** [comment]
I've implemented the expo link here: https://github.com/DiscipleTools/disciple-tools-mobile-app-plugin/commit/9d70901e823c1563381004adcc6ffdecf4cd2c08
I need to get a token somehow to test it.
