### ISSUE TITLE
"Quick_button_phone_off" button not being received by backend [Contact details]

### ISSUE THREAD

**Issue by deividfdez** [DiscipleTools/disciple-tools-mobile-app#11]
The field "quick_button_phone_off" button not being received by backend, we get this error message: “Error code: update_post, error message: One or more fields does not exist”

**Comment by cairocoder01** [comment]
@deividfdez Please provide full steps to reproduce this. Which endpoint? What data are you sending (full JSON body)?

**Comment by deividfdez** [comment]
https://${domain}/wp-json/dt-posts/v2/contacts/${id} (POST)

**Comment by cairocoder01** [comment]
@deividfdez In order to diagnose this, we need to know what is the JSON body that you are sending to that endpoint. Please provide a full example of what you are attempting to do.

**Comment by deividfdez** [comment]
Here is an example

End-point: https://dtappdemo.wpengine.com/wp-json/dt-posts/v2/contacts/540
method: POST

Body:
{
   “relation”: {
       “values”: []
   },
   “coached_by”: {
       “values”: []
   },
   “coaching”: {
       “values”: []
   },
   “baptized”: {
       “values”: []
   },
   “baptized_by”: {
       “values”: []
   },
   “people_groups”: {
       “values”: []
   },
   “groups”: {
       “values”: []
   },
   “subassigned”: {
       “values”: [
           {
               “value”: “117"
           }
       ]
   },
   “overall_status”: {
       “key”: “active”,
       “label”: “Active”
   },
   “seeker_path”: {
       “key”: “none”,
       “label”: “Contact Attempt Needed”
   },
   “type”: {
       “key”: “media”,
       “label”: “Media”
   },
   “assigned_to”: {
       “id”: “18",
       “type”: “user”,
       “display”: “hansrasch”,
       “assigned-to”: “user-18"
   },
   “contact_phone”: {
       “values”: [
           {
               “value”: “1"
           }
       ]
   },
   “contact_email”: {
       “values”: [
           {
               “value”: “1"
           }
       ]
   },
   “sources”: {
       “values”: [
           {
               “value”: “personal”
           }
       ]
   },
   “geonames”: {
       “values”: [
           {
               “value”: “11524838"
           }
       ]
   },
   “title”: “1",
   “quick_button_phone_off”: “0"
}


**Backend response:**
{
   “code”: “update_post”,
   “message”: “One or more fields do not exist”,
   “data”: {
       “bad_fields”: [
           “quick_button_phone_off”
       ],
       “status”: 400
   }
}

**Comment by cairocoder01** [comment]
@corsacca Can you take a look at this? This seems to match the documentation (https://github.com/DiscipleTools/disciple-tools-theme/wiki/Post-Types-Fields-Format) as far as syntax, but I can't get it to work via Postman either.

**Comment by corsacca** [comment]
@cairocoder01 @deividfdez 
This one is on me for not communicating very clearly about the quick buttons.
 The list of quick buttons is variable so the options can be added to or removed from (only through code currently). D.T initially had phone_off in the default list, but we removed it because we felt it would not be helpful in general. The mockups have it because they are based on our instance that has the option. But dtappdemo does not have the field.
Can you check if the other fields word? (quick_button_no_answer, quick_button_contact_established, etc )

Would it be possible to make the list dynamic also on mobile? Display a button for all the fields that start with `quick_button_`. The quick button field settings have an icon field, which works on the desktop version. 

Anyway, if a button is not available in the field list, it shouldn't be shown. https://github.com/DiscipleTools/disciple-tools-theme/wiki/Post-Types has the endpoint for all the settings.

**Comment by deividfdez** [comment]
The button was added
