### ISSUE TITLE
Feature: Pin code for login

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#146]
Allow the user to set up a pin code or fingerprint login so they don't need to enter their password each time.
This will be let the user keep a secure password but be able to log in easily on the mobile app.
![lock-screen-types](https://user-images.githubusercontent.com/24901539/70151875-7a48d180-16ac-11ea-8d4a-98a0733197a8.png)

**Comment by j-oswin** [comment]
What about this? https://github.com/jarden-digital/react-native-pincode

**Comment by deividfdez** [comment]
@zdmc23 is it ok to leave it as option on login and also on settings of the app, so that the user can add it in another time?

**Comment by zdmc23** [comment]
Hi @deividfdez , can you further elaborate on how it would work as an option on login?  I think that it may need to be settings only bc this is the workflow that I was assuming (but please let me know if I have not considered something):

1. User logs into D.T via Mobile App (perhaps first time, or any time), by entering credentials
2. User clicks Settings Tab and enables PIN code option (and executes workflow to setup PIN code, etc..)
3. Subsequent access of Mobile App (Login)
3A. JWT Token is Expired: User is prompted to enter PIN code (and JWT token request happens behind the scenes, and assuming succcess, the user is logged in to the App).
3B. JWT Token is Valid:  If Auto-login has not been disabled (#60), then App opens as normal.  However, if Auto-login *has* been disabled (#60) then user is prompted with PIN code screen.

So to a certain extent, this issue is dependent upon #60 

Please let me know if I have not considered some scenario(s).  Thx!

**Comment by deividfdez** [comment]
@zdmc23 we need a clarification on the deliverable for this issue

1. We have worked for the pin code to activate access to the app, this is available when auto login has been enabled. This is what we understood on the requirements of this issue.
2. Reading 3B further, do you need pin code to login to app if auto login is disabled? If yes this would imply that the user should be online, is that ok?

Please clarify if pin code is only for accesing app content, login (online only) or both.

Thx!

**Comment by zdmc23** [comment]
Hi @deividfdez , 

1. Auto-Login refers to a valid JWT Token + *NO* PIN code or PIN code *NOT* enabled (this is how the app behaves currently after the user has previously logged in and JWT Token is valid).  What you have described is for when PIN Code is enabled.  (Perhaps that is what you intended to say, and we are good?)
1. To clarify, the Settings option should be: "Enable PIN Code" *NOT* "Auto Login".  When the PIN Code has been enabled, then the user is prompted to enter PIN *ONLY* when JWT Token is valid.

The goal of #60 is to prevent the scenario where a user has a valid JWT Token, and someone else accesses their phone.  Currently, an "auto-login" will occur.  However, if the user clicks Settings and toggles "Enable PIN Code", then they should be able to require that a PIN Code be entered to prevent this.

The goal of this issue (#146) is to make the login process more convenient for the user, so that they can enter a PIN which is associated with their login information/credentials (persisted in phone storage - we recognize that this is a security concern, and we will eventually want to warn the user).  For this issue, the flow would be as follows:

1. "Enable PIN Code" == TRUE
1. JWT Token is Expired, no longer valid
1. App makes the login request on the user's behalf when they enter the PIN code
1. JWT Token is now valid, and user can access App without needing to enter URL, username, and password

In the scenario where the login information/credentials are no longer accurate, then user sees error at Login Screen as they normally would if they had mistyped the information themselves.

This issue is somewhat more complex than #60 , so let me know if we want to bump this to next Sprint and only include #60 in current Sprint.

Thx!

**Comment by zdmc23** [comment]
If the app is `offline`, then the PIN code should enable access and continue to work in Offline Mode
