### ISSUE TITLE
Limited contact and group records available

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-mobile-app#149]
A user logged in (via mobile app) to an active instance with thousands of contacts and it brought up 100 contacts and 100 groups in the list.  No option to load more.  The user searched for 5 "active" contacts and none were found.  

I assume that the search is only searching the 100 records that were loaded, rather than all records.

We need all user records available and searchable from the mobile app.

**Comment by jl0325** [comment]
Hi!

On the number of records, the issue speaks of bringing 100 records, but this endpoint is paginated and we would need to modify it, to obtain that amount according to the order parameter they want.We can perform the searches online, but in case the contact is not in the data obtained initially, this can be accessed while the application is online, but when it is offline it would only have the data obtained in the paged endpoint.

**Comment by zdmc23** [comment]
Hi @jl0325 , I think the way that we would want it to work would be to pull the first 100 (preferably most recent and "Active" only, if the endpoint enables this), and then when paginate when the user "pulls-up" on the scroll from the bottom to request additional.

For the search to work, we would probably want to first search the cached local Contacts/Groups, and then if nothing is returned, use the autocomplete search from the endpoint and pull that Contact/Group in if it's returned.

+ @mikeallbutt @ahillbilly @cairocoder01 @j-oswin for additional input

**Comment by mikeallbutt** [comment]
That sounds good @zdmc23 but I would add that all their/the active contacts and groups in the system need to be pulled the first time, even if there are 100+ because not much use having the app if it doesn't have all the active data. But it will be very unlikely that anyone has more than 100 active (as a disciple maker they shouldn't anyway (focus on a few is the best practice)) contacts and groups would be less.

**Comment by cairocoder01** [comment]
I would tend to agree with @zdmc23 about getting extra contacts on demand.

For the sake of efficiency and speed of the app, I don't think we want to get all contacts all of the time. As you said @mikeallbutt, this is an infrequent use case; most multiplier users should have less than 100 contacts. 

There are a number of options that I can see:

1. After initial app load, fire off background task to fetch all of the remaining contacts/groups asynchronously (using a recursive calling of the contacts/groups APIs) so that they are available and stored locally.
2. Do an infinite scroll loading as @zdmc23 described (when you reach the bottom of the list, it loads more). When it loads more, those will inherently be stored locally and available to use and search. This relies on a user scrolling all of the way through their contacts but will require the least amount of work.
3. When doing a search, use the API as @zdmc23 mentioned in order to get other possible contacts not stored locally. We would need messaging if they are offline to inform them that there may be more contacts that couldn't be found because they are offline.
4. When doing a search, retrieve all of the remaining contacts in the list (using a recursive calling of the contacts/groups APIs). This gets the contacts/groups on-demand when they are actually needed. We'll again need messaging if they are offline.

As this is likely an edge case that we shouldn't spend a great deal of time on at the time until we get more multiplier users, I would say we look at the solution that takes minimal effort and has the least impact on the speed and responsiveness of the app.

Options 1 and 4 that require the recursive API calls will have the greatest impact on the speed of the app and its data usage (both in terms of bandwidth and local storage space). Option 2 should be the least amount of effort to implement but won't work well with search since it requires the user to have scrolled through the whole list of contacts/groups. Option 3 would solve that a bit by integrating the search API if the user is online, but that involves some intricacies of balancing online and offline implementation.

With all of that said, I'm not super convinced of any of the options. The combination of options 2 and 3 would be what @zdmc23 suggested and what I initially though, but I think the offline usage of that search API will cause some complications when implementing. The only time we can guarantee that a user is online is when they first login. Since this is an edge case that won't happen often, maybe option 1 will actually be the simplest. I don't like recursive API calls like that, but since most users won't have that many contacts, we shouldn't need to do those background API calls for the majority of users. It will only be people like @mikeallbutt who have a large number of contacts who will need this. Be aware @mikeallbutt that with your previously mentioned performance concerns, this will add to the initial load time of the app when you first login. We should be able to do it asynchronously in the background, but there are already other things we are doing in the background on first load as well, so this will add to those.

**Comment by ahillbilly** [comment]
@cairocoder01, @zdmc23,   While I agree that this seems like an edge case for multipliers, I think that it might be more common than realized.  While a multiplier can't focus extensively on 100s of contacts, if they are working with any type of access ministry, they will be working through many contacts in an effort to find the few that they focus on.  When putting contacts on pause or closed, the contacts stay in the user's list, as they should... but this leads active multipliers to quickly have lots of contacts in their list.   In addition to this, many users (even without an access ministry) are trained to make a list of 100 and work through that list of oikos level relationships.  With this type of training element, any user could start with a full list of 100 or more.

I don't know how this affects the technical solution, but wanted to add to the use case data points.

Prioritizing new and active contacts could go a long way, you'd want to make sure to catch temporary status marks like "Waiting to be Accepted" as well.

**Comment by corsacca** [comment]
Option: use the last_modified date for caching.
When first getting contacts sort use the `sort=-last_modified` param and continue paging until the full list is cached.
The next refresh will usually only need one page and will get the newest changes.

**Comment by mikeallbutt** [comment]
> Option: use the last_modified date for caching.
> When first getting contacts sort use the `sort=-last_modified` param and continue paging until the full list is cached.
> The next refresh will usually only need one page and will get the newest changes.

Thats sounds like a great idea @corsacca because pretty much I would be only accessing people I have had contact with lately. The current list is giving me the oldest contacts first.

**Comment by mikeallbutt** [comment]
Another thing to consider is that although a contact might not have been updated recently, they might be connected with another contact because they listed as a coach or the person who baptised them, or they are in group with them - so these records would be useful to have available too (but whether a user has permission to view them is another issue to consider).

**Comment by deividfdez** [comment]
@zdmc23 @cairocoder01 is there a final decision on this issue? Please let us know so that we can proceed.

**Comment by zdmc23** [comment]
@deividfdez @jl0325 

Please do the following:

- [ ] Retrieve the first 100 Contacts or Groups sorted by last modified date (`sort=-last_modified`)
- [ ] Implement a "swipe up" (kind of infinite scroll) to trigger the `RefreshControl` to retrieve the remainder of the Contacts/Groups
- [ ] Search operates *__initially__*  as it does now by searching the locally cached list
- [ ] But, *__if__* a search does not bring back any results from local cache, then trigger the `RefreshControl` (which will retrieve the remainder of the Contacts/Groups per the bullet point above)
- [ ] (If the user is in OFFLINE mode, then remind them in a Toast that they are offline if they attempt to search and no result is found, or if they attempt to refresh or infinite scroll).

This way, we will hopefully users will get lucky *__most__* of the time and have the Contact/Group that they want in the 100 last modified, but if not, then they still can easily access the remainder

**Comment by zdmc23** [comment]
Load More when there are no more Contacts to load breaks the Search functionality - Steps to reproduce:

1. Have less than 100 Contacts
2. Click `Load More`
3. Search for a Contact (e.g., “Corsac”)

![B7EF8886-F7A5-42E5-8CC4-EED8BA034282](https://user-images.githubusercontent.com/191707/71047670-8c922900-210a-11ea-8f25-039f17813cf4.png)

Proof that it works when not clicking `Load More`

![07EEC95C-E382-4347-B8F5-AFD0C4795C87](https://user-images.githubusercontent.com/191707/71047803-03c7bd00-210b-11ea-83bc-d0312cd7545e.png)
