### ISSUE TITLE
Can't swipe to go back after hitting "Groups" tab

### ISSUE THREAD

**Issue by yorkaspacher** [DiscipleTools/disciple-tools-mobile-app#172]
Under Groups, after swiping to move across the tabs, once you reach "Groups" tab, you can't swipe to go back, it is stuck there. You can touch a tab to go there, but swiping action stops working.
![image](https://user-images.githubusercontent.com/47872338/71097997-f77d4780-217e-11ea-9d36-79463cb08763.png)

**Comment by jl0325** [comment]
HI @yorkaspacher , In the image you can see blue and red boxes, in the case of the red ones they are zones that integrate horizontal Scroll because the groups and their activities are shown there. It is for this reason that the horizontal scroll does not shift the tabs. However, when you scroll through the labels, it changes the tab.

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-19 at 17 53 47](https://user-images.githubusercontent.com/10079527/71217081-96429a80-228a-11ea-96f2-36bc290a7921.png)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10079527/71217126-ac505b00-228a-11ea-8f14-34488a9e50c8.gif)

**Comment by yorkaspacher** [comment]
Grea
