### ISSUE TITLE
Members screen shows total count but only shows active links

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#198]
iPhone via Expo

Steps to reproduce:

1. Select `Grupo acción` Group
1. Scroll to view `Members`
1. Observe a count of 8, but a display of 4

Also, why is the `Hans` icon black while the other 3 are gray?

![CA26B452-13D1-4F74-91F3-85954EF68427](https://user-images.githubusercontent.com/191707/73810102-5f293980-47a3-11ea-978f-c2dbc5c2502a.png)

**Comment by ahillbilly** [comment]
@zdmc23 this (if functioning) mimics the web version.  Basically you can know that there are 8 people in the group, but only have records created for 4 of the 8.  This is a common real use case.

Thoughts on options:
- unnamed dummy records (actual records) - we've thought through several pitfalls with this
- ghost boxes for the four unnamed members with easy options to add new contact or find and attach an existing contact
- a text that says "plus X unrecorded members"
- a text that says "only connected contact records show up in the members list"

Other thoughts:
The Member List section needs to show up (empty) even if the group has no members connected.  I saw one demo where the group said it had four members, but no contacts were connected, so the member list didn't even show up so that you'd know it was there, just empty.  - Is this a separate issue?

**Comment by raschdiaz** [comment]
Hi @zdmc23 @ahillbilly this issue can be closed?

**Comment by ahillbilly** [comment]
There is no way to edit the "member count" like there is on the web app, but it does appear to be mimicing the web app in other ways.  It might be good to include text for when there are no contacts in the group that says that they need to click edit to add people to the group.  Clicking edit all the time is still on odd extra step for me that I forget is needed.  So I see no members, but it takes a bit to figure out how to add members.

**Comment by mikeallbutt** [comment]
> Hi @zdmc23 @ahillbilly this issue can be closed?

I think it can be closed but new issues need to be opened related to the ability to adjust the member count manually
and
what text/message to display when no members are listed.

**Comment by zdmc23** [comment]
Hi @mikeallbutt , we already do have a placeholder for when a Group has no Members:

![ECEC353F-02EA-48E2-B7FC-2A391460B200](https://user-images.githubusercontent.com/191707/76439123-4e677700-6392-11ea-9fcc-b58a2c088392.png)

**Comment by zdmc23** [comment]
@mikeallbutt if you open a new issue for the manual edit (and maybe further describe bc I am not sure what you mean), and reference it here in the comments, then we can close this issue. Thx!

**Comment by zdmc23** [comment]
Moving to a later Sprint bc this doesn't seem to be a high priority

**Comment by ericchen59** [comment]
@zdmc23 I motion to close this issue. I think it's resolved per #375 and 

> Hi @mikeallbutt , we already do have a placeholder for when a Group has no Members:
> 
> ![ECEC353F-02EA-48E2-B7FC-2A391460B200](https://user-images.githubusercontent.com/191707/76439123-4e677700-6392-11ea-9fcc-b58a2c088392.png)

**Comment by zdmc23** [comment]
@ericchen59 Agreed.

Resolved per #375
