### ISSUE TITLE
Scroll menu out of sync

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#243]
Observed on Android

Steps to reproduce:
1. Select Contact
1. Navigate to `Groups` Tab
1. Add some Group which results in error
1. Remove above Group
1. Click `Save` button

Please see video:
- https://youtu.be/jKr8vv1b2dM?t=1205

**Comment by raschdiaz** [comment]
Hi @zdmc23, after a few test we can't figured out why this is happening. Some improvements were made to this flow and it works correctly in new android versions (9), but this visual defect occurs sometimes in older android phones (like 5.0, 5.1, and 7). Apparently this behavior is due to the library itself, so i will create a new issue in their github mentioning this behavior.
