### ISSUE TITLE
Missing data for contacts & groups

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#256]
All the data for a record should be listed when viewing that record.

For example, I have found that on the website a contact has a subassigned person but that person/name is not listed in the subassigned field of the app - most likely because they are not in the most recently updated sort order that was downloaded.

Not having correct/accurate data is a "game stopper" for me.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt .  To solve this, we purpose to remove the pagination of end-points that return this data, but this could affect the operation of the 'Login' process.

**Comment by zdmc23** [comment]
@raschdiaz Loading all of the Contacts does not resolve the issue.  I loaded all, and refreshed the Contact, and still none of the 3 `Relations` Contacts are showing.  I even updated 1 of the 3 with a test comment to ensure that it was recently updated, and it is showing in initial Contact List of 100, and still will not display under `Relations`

**Comment by zdmc23** [comment]
See also #262

**Comment by mikeallbutt** [comment]
This shows what should be seen in the app, but many of the connections are missing. The only ones that show are Nina Kalb for the fields Relation & Baptized by.
<img width="410" alt="Screenshot 2020-03-14 22 36 32" src="https://user-images.githubusercontent.com/43966676/76695409-8a296780-6644-11ea-8165-4361295be5dc.png">

**Comment by zdmc23** [comment]
Hi @raschdiaz , there is a call to "getContactById" which should return the Connection information, so would you kindly explain how pagination has an impact on this?  If removing pagination will resolve this issue and allow us to release v1.2, then we should proceed and then revisit pagination in a future Sprint

**Comment by raschdiaz** [comment]
Hi @zdmc23 ,we need to know what is the amount of data saved on back-end side, to validate if is viable to get all data and save it in local mobile storage. Remember the problems that try to have too much data on mobile storage.

**Comment by zdmc23** [comment]
Hi @raschdiaz , as you recall, we removed the 6Mb local storage default limit from Android (referenced on a previous Trello Card), so we should have the user's entire available disk space to work with.  

We would need you to work with @mikeallbutt to test a change to download the data (since he seems to have the most Contacts/Groups, etc...) and experiment with how long it takes, with which requests can be made AFTER login (in the background), and determine whether it is viable.  Obviously we cannot give you this information upfront; you'll need to experiment.  Thx!

**Comment by raschdiaz** [comment]
I want to comment this possible flow found after testing:
After the testing, I discovered a behavior that we don't take into account when making this change: When you are in OFFLINE mode, create a contact then add this contact to a connection field, this last UPDATE does not work, because the ID of the contact its a autogenerated ID. Currently the mobile does not UPDATE this ID when the contact its saved in the BACK-END.
