### ISSUE TITLE
<- arrow button to show response when pressed

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#275]
The back arrow button (at the top of any contact or group screen) needs to provide a visible response that it has been pressed (like the cancel and save buttons do).

**Comment by zdmc23** [comment]
Hi @mikeallbutt , I am not sure that I understand this... if I select a Contact from the Contact List, and then click the back arrow to navigate back to the Contact List, then why do I need a "toast" to indicate that an action has taken place when clearly it has because I have changed screens.  

Is there a particular scenario, or some popular app functionality, that you have in mind? Thx!

**Comment by zdmc23** [comment]
We `wontfix` this one bc I am not aware of any other common mobile apps that display feedback on every single navigation click.  The screen change itself should be sufficient.  Thx!
