### ISSUE TITLE
Search capability - Contacts

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#28]
Have the ability to search for a contact or group or comment etc.

**Comment by mikeallbutt** [comment]
Like whatsapp which searches all types of lists and sorts them into categories.

**Comment by cairocoder01** [comment]
As shown in design prototype: https://xd.adobe.com/view/7080ce9f-27ae-4018-449e-33b6bcc61293-06b1/screen/55a36009-2711-499c-ad39-cb89387d6aa0/Contacts

![image](https://user-images.githubusercontent.com/44169599/67467550-3abcad80-f649-11e9-8ec5-7d913743c7a4.png)

## Requirements ##
There should be a search box at the top of the contacts list screen that provides the ability to search contacts. It should search the following fields:
* Contact name
* Email addresses
* Phone numbers

## API Integration ##
Current contact list uses the endpoint [/wp-json/dt-posts/v2/contacts](https://github.com/DiscipleTools/disciple-tools-theme/wiki/List-posts), but that does not currently support search. The compact endpoint [/wp-json/dt-posts/v2/contacts/compact](https://github.com/DiscipleTools/disciple-tools-theme/wiki/list-posts-compact) does support search, but it looks like it will only search the contact name and it may not return all of the fields that we need to display on that screen. 

Some API work may be necessary before this issue can be completed. @corsacca Please advise on API suggestions for how this can be implemented.

## Notes/Exceptions ##
* This issue does **NOT** include the filtering feature which shows in the right side of the design above. The filter icon displayed in the design should not be added as part of this issue.
* This issue is for the Contacts screen only - not for Groups as well.

**Comment by corsacca** [comment]
@cairocoder01 the /wp-json/dt-posts/v2/contacts supports both search and filtering. See https://github.com/DiscipleTools/disciple-tools-theme/wiki/List-posts#search-parameters

**Comment by cairocoder01** [comment]
Great! I've updated the requirements above to indicate that

**Comment by jl0325** [comment]
Search contact by email, phone and name is working now.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10079527/69155693-30f36200-0ab0-11ea-95b4-eda55aafe40c.gif)

**Comment by zdmc23** [comment]
When app is reinstalled, and there is no data locally, the Contact List is empty until I enter something in the Search field and the results are cached. Please show all Contacts on fresh install (it works as expected for Groups)

![654C6DA3-F7B4-4916-A73D-82574576EA2C](https://user-images.githubusercontent.com/191707/69165915-5a1bee80-0ac0-11ea-97fb-2238e4bf523e.png)

**Comment by mikeallbutt** [comment]
Hi - Looks good but it doesn't use "i" or "í" (an accented i in spanish) eg. if I type in Ramirez should also offer Ramírez. (It does on the website).

**Comment by jl0325** [comment]
@mikeallbutt  search whit out accented is available, @zdmc23 I'm working to fix that

![Screenshot_2019-11-19-15-28-24-360_host exp exponent](https://user-images.githubusercontent.com/10079527/69183791-a4619780-0ae1-11ea-8415-da0dc410b249.jpg)

**Comment by zdmc23** [comment]
Verified that Contacts display on fresh install. Thx!

![D5DA4820-BE64-48BF-87A0-7FE59EE8762E](https://user-images.githubusercontent.com/191707/69253996-864c7380-0b83-11ea-8e73-44150caa04ec.png)
