### ISSUE TITLE
Link all references to Contacts/Groups

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#308]
On the connections screen, all the connections listed in the various fields will link to the contacts and groups that are listed, so that the user can easily view that information about the contact or group.

**Comment by zdmc23** [comment]
We want to link ANY reference to a Contact/Group

**Comment by raschdiaz** [comment]
We gonna add this links in the 'Detail' views in 'Only View' mode.

**Comment by zdmc23** [comment]
Hi @raschdiaz , it should be every Screen (except Lists, and of course not Login or Settings), but Yes, only in "View" mode

**Comment by raschdiaz** [comment]
Hi @zdmc23 , We have implemented the behavior, We have to add more spaces between Contacts/Groups so the user can tap to redirect him to the corresponding details views. What do you think about this?

[https://drive.google.com/file/d/1FuCWI7ntdigt0cdhB12vfvW7NqQkl4yC/view?usp=sharing](https://drive.google.com/file/d/1FuCWI7ntdigt0cdhB12vfvW7NqQkl4yC/view?usp=sharing)

This is example, We view the 'Señora Saira' contact detail, select an Subassigned contact (Another test contact) and return to previous views.

**Comment by zdmc23** [comment]
Hi @raschdiaz , this looks good!  I assume that you can click link after link and continue navigating between Contacts with no issue, correct? There isn’t some # of clicks where memory or stack builds up and then crashes, I hope.

Please implement the same for Groups.  And also please underline any clickable links, so that the user may distinguish between values that are clickable links vs plain text values.

Thx!

**Comment by raschdiaz** [comment]
Yes @zdmc23, you can navigate between Contacts/Groups with no problem. In my tests I click max 3 times and return. This works as expected. I will add the underline style.

**Comment by zdmc23** [comment]
Thx @raschdiaz !
