### ISSUE TITLE
Share the app

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#315]
As an app user, there are times when I need to inform another user that the app exists and so they can go and download it from an app store. 
Possibly having a "Share app" link on the settings page that goes either iOS or the Play store might work well. Or it might take them to the disciple.tools/app page that offers more info.

**Comment by ericchen59** [comment]
User Story: as a user, I want to share the D.T. mobile app with another person, so that they will be able to download the iOS or Android version of the app

Acceptance Criteria:
- [ ] User is able to click a "share app" button in the kebab (...) menu that allows the user to use the OS share menu to send "https://disciple.tools/download-mobile-app/"
