### ISSUE TITLE
Newest contact is added at bottom of list

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#32]
MexSurfer:
> Currently the newest added contact is added to the end of the contacts  list. This makes for lots of scrolling if you need to find then adjust something you just added. Having a sort order option available would seem very useful. Or just have the newest record at the top (instead of the bottom) might be the simplest solution for now.

New contacts should be visible at the top of the list. The contact list should be sorted by default with the most recently updated contacts at the top.

**Comment by deividfdez** [comment]
@cairocoder01 The end-point ‘/ wp-json / dt-posts / v2 / contacts’ is currently being used, since we need the list to have all the contact data. In this end-point there is no field that indicates the last modification of the contact, we would need a new field that indicates the last modification date. As ‘Workaround’ we sort the lists by ID (new to old)

**Comment by cairocoder01** [comment]
@deividfdez I just tested that endpoint and it does seem to return the `last_modified` field for each contact.

**Comment by deividfdez** [comment]
@cairocoder01 we have solved this issue, can you please check?

**Comment by cairocoder01** [comment]
Works as expected. Thanks @deividfdez
