### ISSUE TITLE
Notifications icon/button with counter

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#349]
The main notifications icon at the bottom of should have a counter / alert when there are unread notifications.

**Comment by ericchen59** [comment]
**Mockup**

<img width="307" alt="Screen Shot 2020-09-18 at 11 53 01 PM" src="https://user-images.githubusercontent.com/26180602/93658520-18bedd00-fa0a-11ea-82e3-173f22278666.png">

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @ericchen59 , See the following video showing the implementation: [https://drive.google.com/file/d/1eP8Is4GGJdS1tOPsl7eLF-KiHMyELKV0/view?usp=sharing](https://drive.google.com/file/d/1eP8Is4GGJdS1tOPsl7eLF-KiHMyELKV0/view?usp=sharing)

**Comment by zdmc23** [comment]
Hi @raschdiaz , when I first logged in the badge does not appear.  It's only when I load the Notifications screen.  Also, when I select `Mark All` the badge does not disappear until I manually refresh.  It's fine to remove on refresh, but then we should force an automatic refresh when clicking `Mark All`

**Comment by raschdiaz** [comment]
Hi @zdmc23 this is because the current Notifications logic, currently, the app get the notifications count only on the NotificationsScreen. We need to get this counter when the user do the login.

On the other hand, when testing the flow of 'mark notification as read' we found some errors. When marking the message as 'read', the counter of the 'unread' messages is not automatically updated. Apparently this error is not recent, since we have not carried out deployments in view of notifications for a long time. We consider creating a new issue for this.
