### ISSUE TITLE
Displaying Custom Tiles and that Custom Tile's Fields data

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#353]
Our DT instance has some custom fields so we need a way to work with that data.

**Comment by zdmc23** [comment]
Hi @mikeallbutt , would you please be more specific here, bc we do currently support custom milestones for instance

**Comment by mikeallbutt** [comment]
> Hi @mikeallbutt , would you please be more specific here, bc we do currently support custom milestones for instance

@zdmc23 - I track involvement/interest a contact has. This is a custom field that is displayed in a custom tile.
Another example would be how to work with data gathered related to the 4 fields strategy for groups - which is different to the church metrics data.

**Comment by ericchen59** [comment]
> > Hi @mikeallbutt , would you please be more specific here, bc we do currently support custom milestones for instance
> 
> @zdmc23 - I track involvement/interest a contact has. This is a custom field that is displayed in a custom tile.
- Can you share two screenshots to describe this more?
- [ ] Screenshot of your DT website, showing how the custom tile shows up in your UI
- [ ] Screenshot of the mobile app, where you'd like to have the custom tile show up in the mobile UI

> Another example would be how to work with data gathered related to the 4 fields strategy for groups - which is different to the church metrics data.
- I think I need more to understand what a _fields strategy for groups_ looks like. I'll ping you on Slack to get some time to hear more abt it.

**Comment by zdmc23** [comment]
@ericchen59 @corsacca @ahillbilly @mikeallbutt 

Let's treat this issue like a Scrum Spike and investigate further to define specific requirements, outline what currently works and doesn't (for example, custom faith milestones display in the mobile app when selected, but there is no opportunity to select them).

Should we also target Custom Tiles (like @mikeallbutt 's "Oikos" Tile) with this issue, or is that deserving of another?

**Comment by ahillbilly** [comment]
I had to google what a Scrum Spike is... but after reading about it, think it is a great idea. 
https://www.visual-paradigm.com/scrum/what-is-scrum-spike/#:~:text=Spikes%20are%20an%20invention%20of,reliability%20of%20a%20story%20estimate.

When it comes to talking about custom tiles and fields, it seems like "modularization" is a key term... how do we get any item that looks like this to act in this same way or be displayed in this same way.

For custom tiles... is there a way to modularize a "tab" on any record type details so that it receives the custom tile name and can be inserted in the swipe-able tabs and can display the custom fields for that tile within it?

For custom fields... they're placed on an existing field or a custom field and usually simply appended to the bottom... Do we want the display of these fields modifiable in the app?
![D_T_Navigation_Flows_–_Figma](https://user-images.githubusercontent.com/25323324/94657493-73edab00-02f9-11eb-8810-c91cc5bf5987.jpg)

**Comment by corsacca** [comment]
List of field types: 
 'key_select', 'multi_select', 'boolean', 'date', 'number', 'user_select', 'number', 'location', 'connection', 'text'

**Comment by corsacca** [comment]
The fields are available on the `/wp-json/dt-posts/v2/{post-type}/settings` endpoint.
I see that the custom tiles are not. I'll add that soon. 

Fields that are part of a custom tile will have `"tile" => "custom_tile_id"` key/value on the field

**Comment by ericchen59** [comment]
@ahillbilly 

> For custom fields... they're placed on an existing field or a custom field and usually simply appended to the bottom... Do we want the display of these fields modifiable in the app?
> ![D_T_Navigation_Flows_–_Figma](https://user-images.githubusercontent.com/25323324/94657493-73edab00-02f9-11eb-8810-c91cc5bf5987.jpg)

- How would the end user expect the order of custom fields to show up on mobile, relative to how they show up on the web? There might be no need to think about this if the web version is already responsive and Custom Tile A, B, C, etc stacks in ascending order.

**Comment by corsacca** [comment]
The settings endpoint now has a list of custom tiles.

https://dtappdemo.wpengine.com/wp-json/dt-posts/v2/contacts/settings will return:
```
...
    "tiles": {
        "a_beautiful_tile": {
            "label": "A beautiful tile"
        }
    }
```

I created a custom tile and a custom field on dtappdemo:
![image](https://user-images.githubusercontent.com/24901539/94934382-8fa4ad00-04c3-11eb-81db-4951e8fb6752.png)

In the future this list will return all tiles (custom and default). And each field that is displayed will be part of a tile in the fields list (instead of being hard coded).

**Comment by zdmc23** [comment]
I love the Tile name @corsacca  :smiley:

**Comment by ahillbilly** [comment]
Additionally, #360 Tags for contact and group records could/should be included in this issue.

**Comment by ericchen59** [comment]
User story: As a user, I want to see all custom tiles and custom fields from my instance to show up in the mobile app, so that I can see all the data that is available to any given contact or group.

**Acceptance criteria:**
- [ ] I can view a contact or group and see custom tiles as additional "pages"
- [ ] I can view custom fields that have been added to any of my tiles

**Mockup**
![94657493-73edab00-02f9-11eb-8810-c91cc5bf5987](https://user-images.githubusercontent.com/26180602/97525717-d7f9a280-197d-11eb-891d-6d252c17c986.jpg)

**API endpoint info**

> List of field types:
> 'key_select', 'multi_select', 'boolean', 'date', 'number', 'user_select', 'number', 'location', 'connection', 'text'




> The fields are available on the `/wp-json/dt-posts/v2/{post-type}/settings` endpoint.
> I see that the custom tiles are not. I'll add that soon.
> 
> Fields that are part of a custom tile will have `"tile" => "custom_tile_id"` key/value on the field



> The settings endpoint now has a list of custom tiles.
> 
> https://dtappdemo.wpengine.com/wp-json/dt-posts/v2/contacts/settings will return:
> 
> ```
> ...
>     "tiles": {
>         "a_beautiful_tile": {
>             "label": "A beautiful tile"
>         }
>     }
> ```
> 
> I created a custom tile and a custom field on dtappdemo:
> ![image](https://user-images.githubusercontent.com/24901539/94934382-8fa4ad00-04c3-11eb-81db-4951e8fb6752.png)
> 
> In the future this list will return all tiles (custom and default). And each field that is displayed will be part of a tile in the fields list (instead of being hard coded).

**Comment by zdmc23** [comment]
Hi @raschdiaz , from the start we will want to consider OFFLINE mode for this issue, similar to our approach in #474 . Thx!

**Comment by raschdiaz** [comment]
Hi @corsacca can you add this data in the dtdemo.disciple.tools instance please? Currently we can't work on the dtappdemo.wpengine instance.

**Comment by ericchen59** [comment]
@raschdiaz can't work on Dtappdemo.wpengine.com because of the 5k+ contacts crash?

**Comment by raschdiaz** [comment]
@ericchen59 the problem seems to be related to the JSON structure returned by the **contacts** end-point, missing several properties (like contact_status).

**Comment by raschdiaz** [comment]
@corsacca which id/names will gonna use on the tiles to the existing tabs for contact ("detail", "progress", "connections") and group ("detail", "progress", "members", "groups")?

**Comment by corsacca** [comment]
@raschdiaz 
Here are there current ids and names:
Contact record
- `relationships` => Connections
- `faith` => Progress
- `other` => Other
- `details` => Details

Group record
- `relationships` => Member List
- `groups` => Groups
- `health-metrics` => Church Health
- `other` => Other
- `details` => Details

**Comment by raschdiaz** [comment]
Hi @corsacca please, can you give some an example custom tile for each field value type? ('key_select', 'multi_select', 'boolean', 'date', 'number', 'user_select', 'number', 'location', 'connection', 'text')

**Comment by corsacca** [comment]
@raschdiaz thanks for asking!
![image](https://user-images.githubusercontent.com/24901539/99808541-51318300-2b41-11eb-84ab-e7b80029cd69.png)

I've added all of them expect `boolean` and `user_select` as the theme does have a "custom" way to display them. You can skip those two for now.

**Comment by raschdiaz** [comment]
We found a problem with the following fields:

Location field: In the web, when we try to set a new value, the field does not show options.

Groups field: This will apply to all "multi value" field like this (select field, location field, multi select field): we are not sure how to relate the value with the respective list (contacts, groups, locations, users. etc). This happens because the app map the JSON before persist it and send the data to the detail view (**we can do the map logic BEFORE SAVE and not AFTER GET in the reducers**. But this change will affect the way we manage the data structure inside all the views (list, detail), and save process)

Date field: This field suffer similar problem related to the JSON mapping, when we map the data, we send a number as string to the view (timestamp), but we cant detect if this timestamp represent a date or a simple number. This can be solved with the solution mentioned above.

**Comment by corsacca** [comment]
@raschdiaz I see the bug on the location field. I'll try to fix it.

The offline behavior i don't fully understand. It seems to me that we already have **connection** and **date** fields implemented in other areas. Could we implement the same logic as there?
@zdmc23 would you be able to add any insight? This is a couple layers deeper than i've explored.

**Comment by raschdiaz** [comment]
Hi @corsacca , we have noticed that the end-point 'wp-json / dt-posts / v2 / contacts / settings' returns the 'type' and 'post_type' of each field:

![image](https://user-images.githubusercontent.com/16809967/100154800-2cf0e180-2e74-11eb-93fd-1f727433fba4.png)

With this info we can know which type of value are using the field.

**Comment by corsacca** [comment]
@raschdiaz awesome.
The locations field should now work as well.

**Comment by zdmc23** [comment]
@corsacca @raschdiaz 

A simple way to think about our offline strategy is that we have is to aggressively get as much data as we can from the API when online, and then order (FIFO) our offline updates to push when back online.  In this case, we would want to leverage the `settings` endpoint to cache the custom tile definition (`type` and `post_type`) when we're online.  An example of a more complex scenario would be if we were online and cached currently available custom field definitions, then went offline only to have those definitions change, and we come back online and would need to detect the mismatch and pull the updated definition.  That'd (hopefully) be rare, but also why I think that we should discuss a hash strategy to know whether records have changed.

**Comment by raschdiaz** [comment]
Hi @corsacca , we check the 'wp-json/dt-posts/v2/groups/settings' end-point but the property "tiles" does not appear.

Contacts end-point:
![image](https://user-images.githubusercontent.com/16809967/100621510-c2b1c400-32ed-11eb-9edd-d4c95a77e3d1.png)

Groups end-point:
![image](https://user-images.githubusercontent.com/16809967/100621546-ce04ef80-32ed-11eb-9930-77632d256ade.png)

**Comment by corsacca** [comment]
Apologies. I missed that setting. It should be available now.

**Comment by raschdiaz** [comment]
Hi @corsacca , in this issue its mentioned that the app can add new fields in the existing tiles (details, relationships, faith). 
Can you add some examples to this flow (contact/group) please?

**Comment by ericchen59** [comment]
@raschdiaz - I didn't see where we said this issue should enable the ability for a user to add new fields (the focus of this issue was to just **view custom tiles and associated data**...can you quote the part of the convo? I read though, but maybe I misunderstood somewhere...

**Comment by corsacca** [comment]
@raschdiaz the other tiles (details, relationship, faith, etc) are not custom and don't currently allow custom fields.
This will be upgraded when v1 of the theme comes out, but isn't ready yet.
So if the functionality works for the custom tiles and custom fields then i'd consider this issue complete.

**Comment by raschdiaz** [comment]
Hi @ericchen59 @zdmc23 @mikeallbutt @corsacca @ahillbilly , as mentioned in the Slack, we complete this issue implementing the custom fields on custom tiles. See the following example video:

[https://drive.google.com/file/d/1ljDvx6JtvafxQkdsVhPMkHpfbYdoYfJZ/view?usp=sharing](https://drive.google.com/file/d/1ljDvx6JtvafxQkdsVhPMkHpfbYdoYfJZ/view?usp=sharing)
