### ISSUE TITLE
Cancel option before switching language

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#355]
@zdmc23 what happens if someone doesn't want to accept the change. There is no cancel or reject change option. I tied to a few things, but all I could do is accept of force close the app. I think it needs an option to reject and not just accept - or a way that gives the app user a way to decline the change.

_Originally posted by @mikeallbutt in https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/328#issuecomment-646387928_

**Comment by ericchen59** [comment]
@mikeallbutt You're talking about adding a "back" or "cancel" button on the dialogue box that shows up when you use the tap path: settings>language? Below is an example of the dialogue box that shows up for me.

![IMG_E1A2F2787F1F-1](https://user-images.githubusercontent.com/26180602/93666905-ed5ee100-fa4f-11ea-84d9-0c2326662323.jpeg)

**Comment by mikeallbutt** [comment]
Yes @eric that is correct. If someone clicks the language ie. English, then that modal pops up, but the only option the app user can currently do is click OK or force close the app.

**Comment by raschdiaz** [comment]
Hi @zdmc23 @ericchen59 See the following demonstration video, doing the 'cancel language change' flow in the settings screen:

[https://drive.google.com/file/d/1ek05bwJO8PmhFAnIuEWgloygQgHmrC3d/view?usp=sharing](https://drive.google.com/file/d/1ek05bwJO8PmhFAnIuEWgloygQgHmrC3d/view?usp=sharing)

Additionaly, another video doing the same flow in the login screen:

[https://drive.google.com/file/d/1emH-0aYKrYM8uoJkAZT93gYHOk6TWaOy/view?usp=sharing](https://drive.google.com/file/d/1emH-0aYKrYM8uoJkAZT93gYHOk6TWaOy/view?usp=sharing)

**Comment by zdmc23** [comment]
Hi @raschdiaz , I have merged the PR, but I do not understand why we need to revert the locale state back in the `i18n.reducer.js`.  If we wait to set the locale upon confirmation, then there would be no need to revert on cancellation

**Comment by raschdiaz** [comment]
Hi @zdmc23 , the reason we implemented the "cancel language change" this way in the SettingsView, is because in this view, when the user select a language, first, we do a request to update the user profile setting. After get the 'success' response, the app will proceed to persist the setting in the state, show the dialog, and after user confirmation, the app will update the i18n setting, and proceeds to restart it.

If the user selects the cancel option, the app will do another request sending the previous config (to update the user profile setting in the web app), receive the 'success' response, update the store and close the dialog.

Unlike the 'SettingsScreen', in the 'LoginScreen', the app only have to update the store and the i18n library language setting.
