### ISSUE TITLE
Reason for contact Status change

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#358]
The website provides a selected choice for reasons a contacts' status is being changed.

- not ready
- paused
- closed

Having the access to this field would be helpful.

**Comment by ericchen59** [comment]
User Story: As a DT mobile app user, I want to be prompted by the app to select the same _reason [not ready, paused, closed]_ as the DT website, so that when I change contact information to [not ready, paused, closed] on the DT mobile app and select a reason, the DT website will reflect the same change

Video Flow of the DT website is [here](https://drive.google.com/file/d/1MXVAF88asr1h1iU17sNUr3IslyHilvKb/view?usp=sharing)
1. Change status
2. When status change to [not ready, pause, closed], dialogue box with options to select appear
3. When status change to any other status, no dialogue box, because no options to select

Acceptance Criteria
- [ ] when a user is prompted to select the same options (from the DT website) for status change to [not ready, pause, closed]
- [ ] when a user can confirm or cancel option selection

**Comment by raschdiaz** [comment]
Hi @ericchen59 @mikeallbutt see the following video showing a example flow:

[https://drive.google.com/file/d/1o27e5givF5lWFhYiLD67K7DA2Ty1-ZiC/view?usp=sharing](https://drive.google.com/file/d/1o27e5givF5lWFhYiLD67K7DA2Ty1-ZiC/view?usp=sharing)

FYI: @corsacca we found that the first option of all contact status reasons not have a label text to show in the dropdowns, please add the remaining texts:
![image](https://user-images.githubusercontent.com/16809967/101968189-d44b7380-3beb-11eb-8c8c-61f09c44ee0d.png)

**Comment by corsacca** [comment]
The label is intended to be empty in the dropdown.

**Comment by mikeallbutt** [comment]
This functionality was lost in 1.10
