### ISSUE TITLE
User not showing in Connection (Relation) List

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#400]
Similar to #338 , we have a situation where a User/Contact IS returned in the `/v2/contacts/1863/` endpoint, but IS NOT returned in the `/v2/contacts` endpoint.  Rather than resolving these for each occurrence (ie, PR #399 ), perhaps we need a more general solution, or even an API change?

+ @raschdiaz  @corsacca 

```
    "relation": [
        {
            "ID": 1774,
            "post_type": "contacts",
            "post_date_gmt": "2020-03-09 19:44:47",
            "post_date": "2020-03-09 19:44:47",
            "post_title": "Hans 1446",
            "permalink": "https://dtappdemo.wpengine.com/contacts/1774/"
        },
        {
            "ID": 63,
            "post_type": "contacts",
            "post_date_gmt": "2018-05-29 14:34:10",
            "post_date": "2018-05-29 14:34:10",
            "post_title": "Christopher Berganza (multiplier)",
            "permalink": "https://dtappdemo.wpengine.com/contacts/63/"
        }
    ],
```

![92F4DA74-43B2-480D-B640-1FCF1D87729F](https://user-images.githubusercontent.com/191707/89464392-632c1900-d73e-11ea-80ff-fe8d83fdf7c2.png)

**Comment by corsacca** [comment]
@zdmc23 I think i understand that the Typeahead is coded to only show values from a certain list (the saved local contacts in this example). The field however has values that aren't available locally. All the typeaheads might.
The website typeahead has a way to pass in custom values [base list]. 
Is there a way to do this on the mobile app? And apply it to all the typeaheads?

**Comment by raschdiaz** [comment]
Hi @zdmc23 @corsacca We consider that a possible solution to this is the following:

When the mobile app get all the contacts (using the end-point 'wp-json/dt-posts/v2/contacts?offset=0&limit=300&sort=-last_modified'), add to this end-point result all related contacts to the list (subassigned, connections), but adding a property that indicates that the user does not have permission to these contacts (boolean). 

This way We can easily filter this contacts to not show them in the 'ContactListView.js' using this new property. And, in the multiple value fields, We can add a general function (similar to 'getSelectizeItems()') to apply the workaround to delete the contact that the user does not have access from the field list when the user remove it from selected values.

Now, We have to found a way to use different contacts list by for each field, because if the user remove a selected value (contact that the user does not have access) and we are using the same contacts list to all field, this workaround will remove this value from all fields that use this list.

**Comment by zdmc23** [comment]
Hi @corsacca , is there any reason for us to display the users/contacts that the logged-in user does not have access to?  If so, we could display the user/contacts without any link - just a fixed text value.  That would more mimic the Website, but is there any good reason for the logged-in user to even know this information?  For instance, is there a way for them to get "connected" to this user/contact that they do not currently have access to?

Hi @raschdiaz , this solution seems good to me.  I know that some other folks on your team are working with D.T theme repository, would they be willing/able to make the PR to update this endpoint, and then @corsacca could review?

**Comment by corsacca** [comment]
@zdmc23 @raschdiaz i don't see why we need to add a whole bunch of records to the v2/contacts endpoint when the information is already available on the records returned from that endpoint. This would slow down the v2/contacts query.
Could the app go through each connection field and add those records to an "extra_records" list if that is needed?

@zdmc23 yes. For example: A contact might be in "Group A" but the user not have access to that group. The user still should see that the contact is in "Group A"

**Comment by zdmc23** [comment]
@raschdiaz , rather than having multiple lists (`unmodifiedContact`, `unmodifiedSources`, `unmodifiedSubassigned`, and now `unmodifiedRelation`) can we just do the same with a single list, or to the differences in type (per Sources and Contacts/Users) make that too cumbersome?

**Comment by corsacca** [comment]
You could have one list for all the connections to "contacts", one list for "group" connections, and a list for the field types like "sources"

**Comment by raschdiaz** [comment]
@zdmc23 @corsacca Actually, these lists exist in the app with the names 'usersContacts', 'sources', 'groups' in the view state.

The problem that mentioned before its the following: the 'usersContacts' list its used in more than one field, if I modify this list (removing some value when the user delete it), it will affect the other fields that use this list.

This implies that I must create separate lists for each field that uses them, so that this workaround only affects the field that the user is removing the selected values.

Another point to consider is the 'undo changes' behavior. This is why I use other lists by field (like 'unmodifiedSubassigned', 'unmodifiedSources'), to store the previous state of the list before the user modifies it by removing some contact 'to which they do not have access'.

**Comment by raschdiaz** [comment]
Hi @zdmc23  @corsacca We add this 'workaround' to ALL fields related.

To Contact Detail: subassigned, relation, baptized_by, baptized, coached_by, coaching, assigned_to, groups.

To Group Detail: assigned_to, group_coach, parent_group, peer_group, child_group, members.

Additionally, we have to do some extra logic to manage the 'assigned_to' fields, to support this implementation.

We done several tests in ONLINE/OFFLINE mode.

Example flow (modifying contact connection relation):

[https://drive.google.com/file/d/1Wsl4OGh8lmeAzqFbPxAXjU3puPyoHlGO/view?usp=sharing](https://drive.google.com/file/d/1Wsl4OGh8lmeAzqFbPxAXjU3puPyoHlGO/view?usp=sharing)

**Comment by zdmc23** [comment]
Hi @raschdiaz , in your demo video, what happens when you click on "Mike A." under `Relation` in `View` Mode?  It looks like it has a link and will attempt to take you to `Contact Details` screen.  Perhaps we should remove the underline/link capability from these sub-list items
