### ISSUE TITLE
Share contacts and groups with other users

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#423]
Like what is available on the website, it will be necessary for some app users to be able to share a record with another user of the instance. This could be done by having a share button in the FAB of a contact or group.

**Comment by ahillbilly** [comment]
In the top right corner of a contact or group detail record is a share icon with the word "Share" after it.  Clicking this opens a modal to display which users the contact record is currently shared with and also allows the current user to add or remove other users from this list.

Currently, a mobile app user is not able to share a record, but needs the ability to do so.

![Screen Shot 2020-10-06 at 11 57 42 AM](https://user-images.githubusercontent.com/25323324/95193079-27a7dc80-07cb-11eb-9e1f-13b672363bf1.png)

@raschdiaz please share what information is needed for clarity here.

**Comment by raschdiaz** [comment]
Hi @ahillbilly, an example of web behavior flow would be helpful. About visual behavior, we consider something like this:

A new option in the FAB, called 'Share'. When the user presses this button, a modal will be displayed with a field to edit the users / contacts to share this contact / group.

This is correct?

**Comment by ahillbilly** [comment]
Before starting work on this, I'd like to get group consensus on the UI placement.  The FAB could work, but it doesn't feel like the right place in context of the other quick actions... 

Let's hold on this and try to get additional feedback.  

The use case though is that I am working with a contact and I know that I will be traveling for a month and my friend or co-worker is going to stay and is willing to connect with the contact, except that he doesn't have access to the contact record and details.  So I will click on the share button, it will open a modal that shows (like all connection fields) the users that currently have access to the contact's record.  I'll click in the field to add my co-worker's user name and the type-ahead will show me the list of names available to connect.  I select my co-workers name from the list and it adds his user to the list of contacts that the record is shared with and on the server side he is granted access (shared) the specific contact record... as if he was assigned, sub-assigned or @mentioned in a comment.  The sharing of permissions is the same for all these forms.

**Comment by ericchen59** [comment]
**User Story**
As a user, I want to be able to share a record so that another user can view, edit, and comment on the contact's record.

**Acceptance Criteria** 
- [ ] Access a share option from a hamburger menu in the upper right corner, to the right of the Edit button
- [ ] user can share and unshare with any other user


**Web version share button (so you can check flow on web version)**
<img width="1057" alt="Screen Shot 2020-10-08 at 12 02 33 PM" src="https://user-images.githubusercontent.com/26180602/95484567-a08b6d80-095e-11eb-86e8-61270f124410.png">

**hamburger icon (in white below)**
![hamburger](https://user-images.githubusercontent.com/26180602/95487113-e433a680-0961-11eb-94a7-4a930a9f8ad7.png)

**Example what the Kebab menu can look like**
![Kebab menu](https://user-images.githubusercontent.com/26180602/95656433-6b0c8e80-0adc-11eb-80f1-f4d851f16c2c.png)

@raschdiaz - let me know if you have additional questions

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 @ahillbilly @ericchen59 see the following video showing the implementation: [https://drive.google.com/file/d/1rn74q3L3SjKUm0o7ylSDQQ1mmk31d4Ai/view?usp=sharing](https://drive.google.com/file/d/1rn74q3L3SjKUm0o7ylSDQQ1mmk31d4Ai/view?usp=sharing)
