### ISSUE TITLE
Toggle for activity and comments 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#44]
Have a way to toggle to view/limit activity and comments.

**Comment by zdmc23** [comment]
The D.T Mobile Website has Filters for Comments/Activities, so the App should have the same

![46E00B25-A08C-46B6-810F-C84742CCCB75](https://user-images.githubusercontent.com/191707/74213670-4cfa4000-4c68-11ea-9466-2413582874be.png)

**Comment by ericchen59** [comment]
**User Story:** As a user, I want to a filter so that, I can select the type of entries in the "Comments and Activity" section, just like I can in the DT Web version.

Acceptance Criteria
-[] Display a _filter icon_ next to the _add comment_ icon (see mockup below)
-[] Tapping on the _filter icon_ slides to a view with checkboxes
-[] View with checkboxes show only options that exist in the contacts "Comments and Activity" section (this is same behavior as DT Web) (see mockup below, please make the Apply button same color as DT)

<img width="327" alt="Screen Shot 2020-10-04 at 1 06 38 AM" src="https://user-images.githubusercontent.com/26180602/95007680-5a41b180-05e0-11eb-8e62-513d5d665252.png">

<img width="386" alt="Screen Shot 2020-10-04 at 1 23 50 AM" src="https://user-images.githubusercontent.com/26180602/95007681-5b72de80-05e0-11eb-8bee-64126b3eecc5.png">

Filter Icon
![Vector 1](https://user-images.githubusercontent.com/26180602/95007693-8d844080-05e0-11eb-8164-6c21d8c025d1.png)

**Comment by raschdiaz** [comment]
Hi @ericchen59 @mikeallbutt , see the following video showing the implementation: [https://drive.google.com/file/d/1fEqtfuuULC9YetHMnSXFByOG5R5DdMnR/view?usp=sharing](https://drive.google.com/file/d/1fEqtfuuULC9YetHMnSXFByOG5R5DdMnR/view?usp=sharing)

In this feature, we implemented the fix to the radio/checkbox tap (related to the issue #415)
