### ISSUE TITLE
Contact Search bar needs to search whole term

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#479]
**Bug:** On the contacts page, when type in a search term, the searching behavior only reacts to the first two letters. See the video here: https://drive.google.com/file/d/1b0KDCBN4aW9C_apLE09scrnjnJyH4Lo5/view?usp=sharing

**User Story:** As a user, I want to be able to type in the partial or full name of a contact so that the contacts list live filters results that match the search term I am typing in

**Acceptance Criteria:**
- [ ] search filters instataneously as user types
- [ ] no limit to search term (currently the search only live filters the first two characters)

**Comment by raschdiaz** [comment]
Hi @ericchen59 we can't see the video, we need to you give us permissions or let the video with public access.

Can you add more details about the 'search live filters as user types' flow?

**Comment by ericchen59** [comment]
@raschdiaz video permission and acceptance criteria updated

**Comment by raschdiaz** [comment]
Hi @ericchen59 see the following video with the fix:

[https://drive.google.com/file/d/1jZvrxIIMJiNKMonMUTAgOlv7TQ1dFQLL/view?usp=sharing](https://drive.google.com/file/d/1jZvrxIIMJiNKMonMUTAgOlv7TQ1dFQLL/view?usp=sharing)

The reason the list does not change, its because the filter does not return results. Now the filter fill show records (or not) according to the current text filter.
