### ISSUE TITLE
Status background colour is missing 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#484]
In the status field of a contact or group in view screen, the background colour is missing and only the outline of the field is coloured at match the status.

**Comment by ericchen59** [comment]
User Story: As an Android OS users, I want to be able to see the background color of the status of my contact so that I can see the text color (in the intended color scheme)

Acceptance Criteria:
- [ ] I can see the background color in the contact status bar
- [ ] I can read the font in the contact status bar

Example from iOS (proper background color)
![Image from iOS](https://user-images.githubusercontent.com/26180602/97526656-fa8cbb00-197f-11eb-89da-2383891afe6d.png)

Example from Android OS (improper background color)
![Screenshot_20201019-094020](https://user-images.githubusercontent.com/26180602/97526713-185a2000-1980-11eb-9047-bd29f69080eb.png)

**Comment by corsacca** [comment]
extra info: The colors should available as a field in the field options.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @ericchen59 see the following video with the fix:

[https://drive.google.com/file/d/12DvUlHQfNGCFG63rRyCZm8-VPZ-84GUF/view?usp=sharing](https://drive.google.com/file/d/12DvUlHQfNGCFG63rRyCZm8-VPZ-84GUF/view?usp=sharing)
