### ISSUE TITLE
Placeholders for (some) components with empty content

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#50]
Have a message displayed on this screen when in offline mode that comments and activity are not available to be shown while in offline mode, but they will appear when back online.

**Comment by zdmc23** [comment]
Hi @mikeallbutt , I edited the Title of this issue to be more comprehensive bc similar situation exists in other places in the App (e.g., List View with newly created D.T instance with no existing Groups and/or Contacts)

If you can think of other scenarios where there would be empty values, then let's document them in the comments on this issue.  For another (potential) example: Notifications; if D.T doesn't auto-add some initial Notifications when creating a new instance, then that's another place.

![placeholders](https://user-images.githubusercontent.com/191707/67160850-eb157380-f322-11e9-949e-c13712fe850f.gif)

**Comment by zdmc23** [comment]
Trello card: https://trello.com/c/Ol8yTd4i

**Comment by mikeallbutt** [comment]
@zdmc23 Thanks for improving this issue. I think you have covered the other places where a place holder would be helpful.

**Comment by mikeallbutt** [comment]
Another thing that would help new app users would be a splash screen that appears the first time they login that gives an overview (brief tutorial) of what they do and where etc.

**Comment by zdmc23** [comment]
> Another thing that would help new app users would be a splash screen that appears the first time they login that gives an overview (brief tutorial) of what they do and where etc.

Mike, I opened up an "enhancement" issue for this: https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/52

**Comment by mikeallbutt** [comment]
The user can't see comments and activity when in offline mode. It is always empty and doesn't even show activity. Having a message mentioning/explaining this would be useful.

**Comment by cairocoder01** [comment]
So I think there are two parts to this: showing that a user is offline and showing that there is no content currently available. They will often go together, but they could also happen on their own.

### Locations for "No Content" messaging: ###
* Contact list
* Group list
* Contact detail - comments/activity
* Contact detail - general 
  * If all we have is the basic information shown on the list screen, we need to give an indication of that
  * This could happen if a user is online to get the list of contacts, then goes offline, and then enters the detail for one of the contacts in the list. We won't have all of the data for that contact (in any of the tabs, not just comments/activity)
* Group detail - comments/activity
* Group detail - general

### Potential Messaging ###
* "**No Contacts (or Groups)** There are not any contacts (or groups) currently available. There may have been a problem getting them from your site. Drag down to try to refresh and try again."
  * If offline, add another line below (with highlighting for emphasis/focus): "You are currently offline. Ensure you are connected to wifi or mobile data in order to refresh and get your contacts (or groups)"
* "**Missing Contact (or Group) Details** This contact doesn't have all of its details from your site. Drag down to refresh and try to get them."
  * If offline, add another line below (with highlighting for emphasis/focus): "You are currently offline. Ensure you are connected to wifi or mobile data in order to refresh and get the contact (or group) details

**Comment by ahillbilly** [comment]
Recommended: 
Use D.T logo image, bold title, message and call to action

**Comment by jl0325** [comment]
Contacts Screen
![WhatsApp Image 2019-12-10 at 17 14 50 (2)](https://user-images.githubusercontent.com/10079527/70573854-c7c3b380-1b70-11ea-8aff-092893917090.jpeg)
Contacts Screen - Offline
![WhatsApp Image 2019-12-10 at 17 14 50 (3)](https://user-images.githubusercontent.com/10079527/70573853-c7c3b380-1b70-11ea-9bfd-042de9145a37.jpeg)
Groups Screen 
![WhatsApp Image 2019-12-10 at 17 14 50 (1)](https://user-images.githubusercontent.com/10079527/70573856-c7c3b380-1b70-11ea-98fc-2eebdd90c7d3.jpeg)
Groups Screen - Offline
![WhatsApp Image 2019-12-10 at 17 14 50](https://user-images.githubusercontent.com/10079527/70573858-c85c4a00-1b70-11ea-8e0f-1acca9666f6a.jpeg)

**Comment by jl0325** [comment]
> * Contact detail - comments/activity

Can you give an example for contact detail?

**Comment by zdmc23** [comment]
For now, let's use the same concept for Group and Contact Comments as well, and if we need to modify it later then we can do so.  Also, I think that in ONLINE mode there will almost always be at least 1 Comment bc D.T Web tracks almost everything in the Comments.  It's probably only OFFLINE mode (like in the screenshot) where we will ever encounter this.

![comments-placeholder](https://user-images.githubusercontent.com/191707/70672206-74bf2e80-1c4c-11ea-8fa9-ecd98c892264.jpg)

**Comment by zdmc23** [comment]
^ obviously change the word `groups` to `contact comments` or `group comments` depending on which context

**Comment by zdmc23** [comment]
@mikeallbutt how does #129 differ from this placeholder issue?  Should #129 be displaying the placeholder and we need to re-open this, or is it a different scenario?
