### ISSUE TITLE
Manual refresh removes search filter

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#508]
When a user selects a filter (e.g., "My Contacts" or a Custom Filter) then the expectation is that a manual pull-down refresh with that filter enabled will simply refresh a query with that same filter.  Instead, the filter is removed and the original list all query is re-run.

Steps to reproduce:
1. Login
1. Select "My Contacts"
1. Select any sub-category (e.g., "Yay! New Contacts")
1. Pull down to manually refresh
1. Observe that filter is removed and all Contacts are refreshed

**Comment by ericchen59** [comment]
User story: As a user, I want to be able to manual pull-down refresh a list that has been filtered by search, so that I can receive any updated information from the server.

Acceptance Criteria:
- [ ] manual pull-down refresh does not remove filter or search terms
- [ ] manual pull-down refresh gets new information that might have been edited from the D.T. web version

**Comment by raschdiaz** [comment]
Hi @zdmc23 @ericchen59 see the following video showing the example flow:

[https://drive.google.com/file/d/1oGU_wtbJDX4b3p5aSA5EqaqoY5X4u6Fi/view?usp=sharing](https://drive.google.com/file/d/1oGU_wtbJDX4b3p5aSA5EqaqoY5X4u6Fi/view?usp=sharing)

In the video, we show 2 flows:

- Update the contact 'hans 1024' status from 'Paused' to 'Active' on web, and then refresh the list in the mobile app.
- Update the contact 'hans 1024' name to 'hans 1024 test adding long name!', and then refresh the list in the mobile app.
