### ISSUE TITLE
Sub-assigned to list choices do not match the DT web version

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#516]
![Screenshot_20201116-091246](https://user-images.githubusercontent.com/26180602/100969271-d7b27100-3500-11eb-904f-7f6c7c1c2b41.png)
![Screenshot_20201116-091609](https://user-images.githubusercontent.com/26180602/100969273-d8e39e00-3500-11eb-9c2b-634c0b0226f8.png)

**Comment by raschdiaz** [comment]
Hi @ericchen59 @zdmc23 see the following video with the fix:

[https://drive.google.com/file/d/1-8WEU02W7SenJOZvfFZhpMxF_mhhDZQo/view?usp=sharing](https://drive.google.com/file/d/1-8WEU02W7SenJOZvfFZhpMxF_mhhDZQo/view?usp=sharing)

FYI: Its possible that some contacts don't appear in some fields like this, because the pagination of the app (currently set to 1000 records) . For the moment, the pagination limit its 1000 because the 'app crash' problem reported previously:[https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/497](https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/497)

**Comment by ericchen59** [comment]
From @mikeallbutt - still have issue. Asked Corsac a diagnostic question.

<img width="766" alt="Screen Shot 2021-01-07 at 3 47 37 PM" src="https://user-images.githubusercontent.com/26180602/103943211-ac263600-50ff-11eb-91d8-905b0d7dea49.png">
