### ISSUE TITLE
Custom Filter does not show contacts available on web version

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#532]
Selecting a custom filter on mobile app does not load any contacts

Flow: https://drive.google.com/file/d/1T0dUxnk8vs9SaQ64U8clSK5kt751F96J/view?usp=sharing

**Comment by raschdiaz** [comment]
Hi @corsacca, how the custom date filters work?

We did a test creating multiple filters on the website and we noticed the following behavior:

The first filter uses the 'created_on' property (but contacts 'endpoint' don't return it), do we have to use it as if it were the 'post_date' (contact / group creation date) property?

![image](https://user-images.githubusercontent.com/16809967/102930976-7cbeca80-446b-11eb-9026-7b2c2f93ec66.png)

The second filter created uses a custom field called 'date_test'.

![image](https://user-images.githubusercontent.com/16809967/102930956-729ccc00-446b-11eb-8c7f-32dc9bc911e4.png)

The third filter created does the same as the second filter.

**Comment by corsacca** [comment]
@raschdiaz , In a few weeks the "created_on" field will be changed to "post_date". See [change docs](https://github.com/DiscipleTools/Documentation/blob/master/Theme-Core/Revisions/v1.0.0-dev-changes.md#consistently-using-post_date-in-the-api)

Then it will be consistent with what the endpoint returns.
So yes, please use "created_on" as post_date

**Comment by raschdiaz** [comment]
Hi @ericchen59 @corsacca see the following video with the implementation:

[https://drive.google.com/file/d/1p6dMmCfxc7C5evTNh7W1P_GAcFMcrrZL/view?usp=sharing](https://drive.google.com/file/d/1p6dMmCfxc7C5evTNh7W1P_GAcFMcrrZL/view?usp=sharing)

But we found two problems:

- We can´t implement the "Shared with me" filter, because the mobile app does not get any info related to this data ('wp-json/dt-posts/v2/contacts')

![image](https://user-images.githubusercontent.com/16809967/103313223-65dd2280-49ed-11eb-8c40-8293725005f6.png)

-The "Peer Group" filter (groups) does not work in the web app.

**Comment by corsacca** [comment]
Is making the query an "online only" query an option?
Where it would not validate against the local contacts, but run the query to the server an show the contacts returned.
