### ISSUE TITLE
Group Members tab screen

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#57]
Have access to viewing and editing which members are in a group.

<img width="257" alt="Screenshot 2019-10-23 11 04 43" src="https://user-images.githubusercontent.com/43966676/67412389-ccaeb280-f584-11e9-93ed-ad0e56588a90.png">

**Comment by cairocoder01** [comment]
## Requirements ##
* Add "Members" tab to group detail screen
* Tab should replicate the "Members" panel on the web version
* Tab content should be a list of all members assigned to that group
* Each member should have a delete icon to the right of it. When tapped, it should remove the contact from the group and save immediately (no edit screen)
* Each member should have an icon to indicate if they are a leader. On the web, that is a foot. When tapped, it should set/unset that contact as a leader and save immediately (no edit screen)
* Tapping on a member should link to the appropriate contact detail screen
* At the bottom of the list, there should be a contact select list in order to add a new member.
  * It should use the same control as the Assigned To field in contact details but with a list of contacts instead of a list of users. The control needs to allow search.
  * On selection of a contact, it should add that contact as a member of the group immediately (no edit screen or waiting to save)
* For now, we will not replicate the feature from the web that allows creation of a new user to be a member of a group. We will create a separate issue for that feature.

![image](https://user-images.githubusercontent.com/44169599/67499081-c1d94800-f680-11e9-9130-0864d5415b4b.png)

**Comment by jl0325** [comment]
Hello, I make the first commit of this issue, the member window is available.

However, we found the following problems on which they are working:

- When you return from the contact detail, redirect to the contact list

- the order of the contacts to be added is not like that of the requirement

- I am doing the offiline tests

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/10079527/69458852-54334100-0d3e-11ea-9744-a06c06bbd5d8.gif)

**Comment by jl0325** [comment]
I'll working to complete these requirements, in the same way that I carry out the PR.

**Comment by mikeallbutt** [comment]
Great that this has been implemented. When there are no members, it might be good to show a help message (under the Members heading where the list of members would normally be seen) to add a member using the Add Member field.

**Comment by zdmc23** [comment]
> Great that this has been implemented. When there are no members, it might be good to show a help message (under the Members heading where the list of members would normally be seen) to add a member using the Add Member field.

@mikeallbutt That would relate to #50 for Placeholders. We will include that in the next Sprint
