### ISSUE TITLE
Advise when app is offline

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#58]
Keep the app user informed that the app is offline. This might included greying out or disabling refresh button/system/action. Or having an icon in the header that is always present showing either online or offline and if clicked will switch to the settings slider to engage or disengage the on or offline mode. 

Offline
![journey-offline](https://user-images.githubusercontent.com/43966676/67416350-557d1c80-f58c-11e9-8499-e38430472ba1.png)
Online (maybe the cloud icon could have a tick in it too)
![journey-online](https://user-images.githubusercontent.com/43966676/67416351-557d1c80-f58c-11e9-8882-7926bf3ae59c.png)
Syncing
![journey-sync](https://user-images.githubusercontent.com/43966676/67416352-5615b300-f58c-11e9-9f87-26a82f015ef0.png)

**Comment by mikeallbutt** [comment]
Should not be able to request a refresh of a page when in offline mode.
Message needs to be displayed saying offline therefore refresh not available.

**Comment by mikeallbutt** [comment]
An icon like this could also be used.

![disconnected-icon-18](https://user-images.githubusercontent.com/43966676/67427057-f4137880-f5a0-11e9-975c-f730bd95182f.png)

**Comment by cairocoder01** [comment]
@mikeallbutt What do you think of these two options? Since we have the toggle for online mode in the settings, and since the tab nav is the most visible, that seems like the most logical place for it. Especially since we use the header for different things on most screens besides the list screens.

The first is the icon we are currently using on the settings screen for online mode.
The second is the closest I could find to what you suggested in our default available icon sets (`wifi-off` from MaterialCommunityIcons)
![image](https://user-images.githubusercontent.com/44169599/67501292-52fdee00-f684-11e9-8f48-31173479336b.png)

**Comment by mikeallbutt** [comment]
> @mikeallbutt What do you think of these two options? 

I think the information that the app is offline needs to be displayed on any screen (except maybe in edit mode). So since the bottom Settings icon is not always visible, but the header is, then can we find a suitable location in the header? Far right side? But I see your point too about using the header for other things, and it might not be the best place for such an icon.

When Facebook/Messenger is offline, it displays a message under the header that informs people that not all data is available. That might be a good solution for us too.

![Screenshot_20191024-131853](https://user-images.githubusercontent.com/43966676/67513677-f3dab200-f660-11e9-81df-4e4e817eef43.png)

IMO - @cairocoder01 your icon options are ok but not obvious enough for many users as to what might be happening. The second icon using the red crossed out wifi symbol is better than the lightning bolt (which I think we should replace in the settings screen too.)

I think this icon below is a really good choice. Wifi symbol indicates being online while the exclamation mark informs that there is an issue. With DT working offline and saving data while offline, there is not a problem. We just need the user to be informed that once back online, the data will be synced.
> ![disconnected-icon-18](https://user-images.githubusercontent.com/43966676/67427057-f4137880-f5a0-11e9-975c-f730bd95182f.png)

Maybe like what Journey app does, when you click on the cloud icon, it opens a modal that gives relevant information. Maybe for us it could have the toggle slider showing if the app is online or offline. And when the data was last synced.

![Screenshot_20191024-125746](https://user-images.githubusercontent.com/43966676/67512316-2931d080-f65e-11e9-9103-adfd5210db7c.png)

**Comment by cairocoder01** [comment]
My original thought was actually a small banner like Messenger as well. Because of our mixed usage of the header and tab nav for various purposes, I think that might be one of the best and clearest solutions. It will only require a minimal amount of vertical space so should affect the available screen real estate too much.

![image](https://user-images.githubusercontent.com/44169599/67677655-41229080-f98d-11e9-95be-1147edeab3f9.png)

**Comment by mikeallbutt** [comment]
If we did want to use icons, then these ones I made could be useful.

*Offline alert - data is being saved and will be uploaded when back online*
![mode-offline](https://user-images.githubusercontent.com/43966676/67717922-47683b00-f994-11e9-8787-1478839b8166.png)

*Online - all data is being saved*
![mode-online](https://user-images.githubusercontent.com/43966676/67717923-47683b00-f994-11e9-9456-27e1057b0017.png)

**Comment by cairocoder01** [comment]
Let's go with the simple Messenger-like banner that I showed in the most recent comment above (https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/58#issuecomment-546920199).

## Requirements ##
* When app is in offline mode...
  * Show thin banner below header bar with text "Offline"
    * Background color: #FCAB10
    * Height: 20
    * Font size: 14, color: white
  * Banner should show on every screen in the app (as long as the header bar is visible
  * Pull to refresh should be disabled on contact and group list screens
* When app comes back online, offline banner should disappear

**Comment by zdmc23** [comment]
The banner is part of the scrollable view, but it should be attached to the Header and viewable on any screen with a Header (and unaffected by scrolling)

![871D4FC7-9A6A-4D33-AEB0-74E063FF1E5A](https://user-images.githubusercontent.com/191707/69584811-1cc9cc00-0fac-11ea-9bb0-0f9bdea97e50.png)
![10AF4325-E6C4-4B73-895B-E90B279BA030](https://user-images.githubusercontent.com/191707/69584812-1cc9cc00-0fac-11ea-9d7a-f8c4a33bcf04.png)
![270ED6C8-C89A-469C-B08F-939DAAA0A52F](https://user-images.githubusercontent.com/191707/69584813-1cc9cc00-0fac-11ea-9996-7db63cfca752.png)

**Comment by jl0325** [comment]
the last PR have the advise on contacts and groups list.

About "Pull to refresh should be disabled on contact and group list screens". I would like talk because this action is available in offline yo force the refresh  when the device can't load the changes at the first time. This usually happens on cell phones with low memory

![WhatsApp Image 2019-11-26 at 8 02 41 AM (3)](https://user-images.githubusercontent.com/10079527/69635921-73beb800-1023-11ea-99cd-02d525a21a8f.jpeg)
![WhatsApp Image 2019-11-26 at 8 02 41 AM (2)](https://user-images.githubusercontent.com/10079527/69635925-77523f00-1023-11ea-8b07-5133a62fe8db.jpeg)

**Comment by jl0325** [comment]
Working to do unaffected by scrolling!

**Comment by jl0325** [comment]
The new PR! 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10079527/69654045-23a31e00-1042-11ea-9af1-2358d1bce76d.gif)

**Comment by mikeallbutt** [comment]
How possible would it be to have the offline message not move every time a user changes a tab. Can the message be fixed/static in that position?

**Comment by mikeallbutt** [comment]
The offline message does not appear when adding a new contact or group, on the settings page, in edit mode of Group details, Progress or groups tab (members tab it does though).
