### ISSUE TITLE
Unable to Login from Android devices.

### ISSUE THREAD

**Issue by Elliott-Song** [DiscipleTools/disciple-tools-mobile-app#614]
Our instance works perfectly for iOS devices but on Android devices, once the correct credentials are entered and submitted in the login screen, a loading wheel appears and nothing changes after that point. Even when the app is exited and re-entered, the loading wheel remains.
![Error](https://user-images.githubusercontent.com/58920978/144771723-2eb8f393-1e8e-4e33-a8f4-21ee07a2fbf0.jpg)

**Comment by zdmc23** [comment]
Hi @Elliott-Song , thx for opening the issue!  Yes, this is a known problem for Android devices, and we have a few workaround options that we can make available to you.  Are you in the D.T Slack already?  If so, check out the #mobile-app-dev channel.  If not, message me a preferred email and I will send you an invite and we can discuss.  Basically, the options are: (1) sideload the v1.9.2 APK, or (2) for us to add you as an Expo project member so that you can load v1.9.3 via the Android Expo app (which several folks have verified to be working properly).
