### ISSUE TITLE
Way to request a lost your password

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#65]
On the login screen, there is a text link that says “Lost your password?” but nothing happens when the link is clicked.

**Comment by cairocoder01** [comment]
Assuming a user has entered their DT URL, we could just link to the web-based forgot password page for now: `{dt-url}/wp-login.php?action=lostpassword`

Should we hide/disable the forgot password link until a user enters the URL? I think it would be helpful to keep it visible so that people see it is an option, but maybe if they tap on it before there is a URL entered, we give a quick pop-up asking them to enter their URL first. I would think that the main use case is that someone fills out all three fields, gets an error that the password is wrong, and then click forgot password, so that disabled message would not be a common case.

As such, here is what I would recommend:

* [ ] Disable forgot password link until URL is entered
* [ ] If disabled forgot password link is tapped, display message saying "Please enter URL to start to retrieve your password"
* [ ] When forgot password link is tapped, open link in browser to `{url}/wp-login.php?action=lostpassword`

**Comment by mikeallbutt** [comment]
> As such, here is what I would recommend:

The option to show the password will help incase they simply typed it in slightly wrong.

**Comment by cairocoder01** [comment]
@mikeallbutt Agreed. Could you make another issue for that since it is separate from the lost password functionality?

**Comment by mikeallbutt** [comment]
> @mikeallbutt Agreed. Could you make another issue for that since it is separate from the lost password functionality?

Issue #81

**Comment by zdmc23** [comment]
Verified on iOS (the Link is not visually disabled, but it is programmatically disabled and prompts the toast feedback, so that’s probably fine since a user action has been taken)

![A8402E00-F152-480C-A9BB-FB6DF9CA14EA](https://user-images.githubusercontent.com/191707/72683127-8d6c0100-3aa2-11ea-9a56-c4f27b401055.png)
