### ISSUE TITLE
Filter by type is wrong on comments and activity screen 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#688]
One of the 3 filter types should be being stated but instead it says `favourite contacts`

![IMG_20220621_230057.jpg](https://user-images.githubusercontent.com/43966676/174940877-563e0d61-27c2-462c-9e64-1ff58ececdd2.jpg)

**Comment by MaxwellDG** [comment]
![293490889_5235001589901313_5943742851326503170_n](https://user-images.githubusercontent.com/51105802/180337244-6baf9f4d-8d72-470f-bca5-6865f2173009.png)

I believe this issue has been solved too. This screenshot was taken on the Comments and Activity Screen after navigating from a Contact. Maybe the issue is happening elsewhere in a specific instance of Comments and Activity Screen? @mikeallbutt Can you confirm?
