### ISSUE TITLE
Investigate FlashList

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#702]
Investigate any UI/performance improvements gained by a potential migration to https://shopify.github.io/flash-list/

**Comment by zdmc23** [comment]
See #673

**Comment by MaxwellDG** [comment]
Flashlist looks alright, but I'd also like to suggest RecyclerListView https://github.com/Flipkart/recyclerlistview. I've used this list before for infinity scrolls and it has no loss in performance while scrolling to heavy list items at indexes in the thousands. 

I presume your suggestion is in regards to the general lag of the app while interacting with large lists? I took a bit of a look at what could be causing that, and I believe there's more than 1 factor to this (the type of list component is definitely one of those). The other thing is that there are a few full-list iterations going on. From a brief overview yesterday, I already found 2 instances of the entire array getting iterated on page load. That's way too heavy when the list is in the several thousands. 

In addition, some pagination would really help. I read the post regarding how all data must be sent on load because of offline data-caching. While that may be true, I believe there are better ways to do that. You could have a fetching service that does this gradually in a background thread. It certainly shouldn't be being done on the main thread on page load every time.

**Comment by zdmc23** [comment]
Hi @MaxwellDG !  Happy to have your help!

FlashList is using RecyclerListView (ref: https://github.com/Shopify/flash-list/blob/5c6fb9a28baf3ea2f37ee030a93a60db4354e4b4/src/FlashList.tsx), but we are fine removing the abstraction and using that component directly if you have some code to reuse or feel it would make for a better implementation.  Spotify shared FlashList recently and it was making the rounds on social media, but we don't have a particular preference.

Yes, we are looking to prevent app lag.  We are aggressively fetching lists (all is the default), but the user can also fetch by filter (eg, Favorites).  This is also somewhat of a byproduct of the decision to use SWR (https://swr.vercel.app/) to fetch data and serve as an in-memory cache (that we then use to write to persistent storage when the App is backgrounded, etc...)

Pagination gets a little tricky with SWR because it caches results based on the URL, and bc we cannot guarantee that the D.T API will return us the same results of an paging offset, it makes for some challenges.  SWR does return the data initially from cache and then fetch in the background and attempts to validate/invalidate, so while the initially loads of thousands of users will take a few seconds, subsequent fetches should return quickly and then refresh the cache in the background automatically.

**Comment by MaxwellDG** [comment]
Yea nice to meet you @zdmc23.

Okay sweet I didn't realized it was using RecyclerListView under the hood. That's great then. I do have some reusable code there, but let's just go ahead with using FlashList. I'm sure while it's being built there will be several parts I could integrate what I've got.

And I'll have to look more into SWR then too. It's only my first day looking at this codebase, so I'm sure you have many reasons for things that I haven't fully understood yet lol. Regardless, FlashList looks like it'd be a relatively easier change to make than the alternatives. And it won't mess with any of the other solutions either. So I agree that should be the first step.
