### ISSUE TITLE
Improper ref use warnings on LoginScreen and general refactoring

### ISSUE THREAD

**Issue by MaxwellDG** [DiscipleTools/disciple-tools-mobile-app#704]
Hi everyone,

I'm new to this repo and was sent here by @mikeallbutt. I'm part of the Puerto Escondido chapter down here and was excited to hear that you have an app in development. I'm a professional frontend developer with 5 years experience (2 years in React Native) and I'd like to contribute where I can.

To get more familiar with the general feel and workflow of the app, I decided to look at LoginScreen first. Especially because there were some warnings there on startup.

**Issue:**
- Warnings on app loading about improper ref usage
- General refactoring for code bloat on LoginScreen.js
- Several components could be combined into one which would have a larger amount of reusability across the app (Namely 'LabeledTextInput.js')

**Comment by zdmc23** [comment]
Hi @MaxwellDG , we are happy to have your help!  Thanks for jumping right in and reviewing the code!

It's up to you whether you want to refactor LoginScreen just yet, bc we have a change coming soon to punt login to the Web via OAuth2 (we have a PoC - the open web browser flow, and then redirect control back to the app once authenticated).  The reason for this is that we have received several requests for 2FA/MFA and other authentication-based plugins, and it's not feasible for us to support them all in-app.  We did have an initial 2FA implementation, and it works fine, but we needed to standardize on a particular 2FA WordPress plugin in order to validate the code according to that plugin's DB table name, schema, etc... It quickly becomes impractical when we're supporting hundreds of instances all using a different set of auth plugins that we cannot control.  We could modify our Mobile App plugin to be OAuth2 Server compliant, but haven't had the time, and also some teams want to stick with what they already have installed.  TL;DR: it is simpler to just punt authentication to the Web and then teams can have any combination of plugins they want, or use Azure AD (without us needing to figure out how to get the appropriate Tenant IDs, etc...)

All that to say that Login may be changing significantly, so I leave it up to you how much time you want to invest there.  Maybe there are some quick wins around ref forwarding, and component reuse and if so, go for it.  Thx!

**Comment by MaxwellDG** [comment]
That's good to know. I should probably ask beforehand next time. I've written something up right now and I'll submit it tomorrow night. It sounds like it'll get overwritten soon but it's cool. It was mostly for me to have a specified task while I browsed the codebase.

**Comment by zdmc23** [comment]
No worries, I realize we currently have very little documentation to help onboard to the project.  Once we get this release out, I will try to get on that and highlight some rationale and maybe where a decision seemed good at first but could be improved upon, etc... 

PS. We still may end up keeping the Basic Auth flow for teams who do not want to deal with an extra OAuth2 Provider plugin, so I don't think any of your work will be in vain.

PSS. Check out https://github.com/DiscipleTools/disciple-tools-mobile-app/blob/development/components/Field/Text/TextField.js , there may also be some opportunity to reuse any text input components there too

**Comment by MaxwellDG** [comment]
@zdmc23 Hey is there another place we could discuss the project? Are you using Slack, or Trello, or Asana or anything like that? A discord channel maybe?

Cause I've been trying to do 2 smaller issues (#700 and #688) and as far as I can tell they've already been completed. I'd rather not keep searching through the issues if lots of them are already completed.

**Comment by zdmc23** [comment]
@MaxwellDG , we have a private Slack, please DM me an email that you want me to use for invite. Thx

**Comment by MaxwellDG** [comment]
@zdmc23 maxwellmdg@protonmail.com

**Comment by zdmc23** [comment]
@MaxwellDG Thx for the PR on this, it looks better!  Just one thing, when I change the language, the TextField labels are not being updated bc of the memoization being based on the key (which doesn't change - same English key regardless of locale):

`const text = React.useMemo(() => i18n.t(i18nKey), [i18nKey])`

If we still want to memoize, then something like the following would prob do the trick:

`const text = React.useMemo(() => i18n.t(i18nKey), [i18n?.locale])`

Thx!

**Comment by zdmc23** [comment]
Resolved by https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/709
