### ISSUE TITLE
Pulling down to refresh the list screen does not reload list items 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#736]
Many times when I do a pull down from the top of a list screen to activate a screen list refresh, the action is noted becuase the list items move/expand a bit, but then on release, the list doesn't refresh.

The reason I have been trying to reload manually is that changes have been made in the records like assign a record to be a favourite, but once I leave the record I don't see the change reflected in the list. Same things occurs when adjusting the status of the user from active to paused.

**Comment by zdmc23** [comment]
The Refresh Control is a native RN component; sometimes you just need to pull down a little further and you should see the Activity Indicator (Spinner) to denote that it has taken effect.  The List information being updated is something that we plan to fix in another issue and it is due to offline cache needing to be updated in 2 places (List and Details) for some information
