### ISSUE TITLE
Reveal password on login screen

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#81]
Have the way to reveal the password on the login screen. This would be off but default.

This will help incase they simply typed it in slightly wrong and then they don't have to go through the whole process of changing their password.

**Comment by jl0325** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/10079527/72118000-abf13000-331d-11ea-8d86-159c406162b9.gif)

**Comment by zdmc23** [comment]
First 2 chars are not visible when entering on iOS (iPhone XR). Upon entering 3rd char, 1st remains hidden and 2nd is partially hidden. Once you click the icon to show text or to hide, then it seems to display properly.

**Comment by zdmc23** [comment]
Also there is an ellipse (3 dots) showing, please resolve this 
![EA2FC99D-DF5A-4BDC-8D0C-83633CACDA63](https://user-images.githubusercontent.com/191707/72683141-b9878200-3aa2-11ea-96f3-77d980b122ee.png)

**Comment by zdmc23** [comment]
2 additional issues:

1. When typing in password, sometimes an ellipse (... 3 dots) follows the text. I cannot share screenshot bc iOS will not capture content in password field in screenshot
1. In order to select into the password field to type, you now have to select far to the left side, clicking in the middle of the field does nothing
