### ISSUE TITLE
Login error message more useful

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#89]
When someone tries to login and enters an incorrect username or password, they get this VERY red coloured error message with HTML code displayed.

![Screenshot_20191106-132521](https://user-images.githubusercontent.com/43966676/68330916-abc48200-0099-11ea-9095-eb34c09058a8.png)

I suggest that the message isn't so "harsh" in appearance and that the message is a bit more app user friendly.

**Comment by cairocoder01** [comment]
I think this can go along with #87 to clean up our toast/pop-up notification bubbles.

We should not use the raw message returned from the API. As a simple fix, we could strip all of the html from the message field of the api response and show just text. However, in this example, that will still show "ERROR" and the lost password link. We could use regex to strip out any links from the message as well.

The other option is that we find all of the error codes (e.g. `invalid_username`) and write our own error messages for them. This also means we will need translations for those error messages.

We will need to identify/compile a list of all of the different error messages that could be returned here so that we can write better user feedback for them.

**Comment by jl0325** [comment]
![WhatsApp Image 2020-01-21 at 10 53 41 AM (1)](https://user-images.githubusercontent.com/10079527/72820130-706b3580-3c3c-11ea-84e5-27993392799e.jpeg)
![WhatsApp Image 2020-01-21 at 10 53 41 AM](https://user-images.githubusercontent.com/10079527/72820132-7103cc00-3c3c-11ea-95d6-bdbdedc8deb4.jpeg)

**Comment by cairocoder01** [comment]
Can we remove the Code as well as the label for Message so that we only show the message itself? Users don't care about the error code and might get confused by it, especially since it is the first think in that error box.
